# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20, unique=True)),
                ('s_create_time', models.DateTimeField(auto_now_add=True)),
                ('s_operate_time', models.DateTimeField(auto_now=True)),
                ('s_img', models.ImageField(null=True, upload_to='upload')),
                ('s_language', models.IntegerField(default=0)),
                ('s_math', models.IntegerField(default=0)),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grades')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
